# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QueueCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QueueCheck

  # Firebase pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  # AWS Amplify pods
  pod 'Amplify', '~> 1.0'
  pod 'Amplify/Tools', '~> 1.0'
  
  pod 'AmplifyPlugins/AWSAPIPlugin'

end
